# Generated by Django 3.2 on 2022-03-25 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pose_name', models.TextField()),
                ('pose_description', models.TextField()),
                ('pose_type', models.TextField()),
                ('user_duration', models.FloatField()),
                ('nose_x', models.FloatField()),
                ('nose_y', models.FloatField()),
                ('leftear_x', models.FloatField()),
                ('leftear_y', models.FloatField()),
                ('rightear_x', models.FloatField()),
                ('rightear_y', models.FloatField()),
                ('lefteye_x', models.FloatField()),
                ('lefteye_y', models.FloatField()),
                ('righteye_x', models.FloatField()),
                ('righteye_y', models.FloatField()),
                ('leftshoulder_x', models.FloatField()),
                ('leftshoulder_y', models.FloatField()),
                ('rightshoulder_x', models.FloatField()),
                ('rightshoulder_y', models.FloatField()),
                ('leftelbow_x', models.FloatField()),
                ('leftelbow_y', models.FloatField()),
                ('rightelbow_x', models.FloatField()),
                ('rightelbow_y', models.FloatField()),
                ('leftwrist_x', models.FloatField()),
                ('leftwrist_y', models.FloatField()),
                ('rightwrist_x', models.FloatField()),
                ('rightwrist_y', models.FloatField()),
                ('lefthip_x', models.FloatField()),
                ('lefthip_y', models.FloatField()),
                ('righthip_x', models.FloatField()),
                ('righthip_y', models.FloatField()),
                ('leftknee_x', models.FloatField()),
                ('leftknee_y', models.FloatField()),
                ('rightknee_x', models.FloatField()),
                ('rightknee_y', models.FloatField()),
                ('leftankle_x', models.FloatField()),
                ('leftankle_y', models.FloatField()),
                ('rightankle_x', models.FloatField()),
                ('rightankle_y', models.FloatField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_earned', models.IntegerField()),
                ('pose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pose')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile')),
            ],
        ),
    ]
