# Generated by Django 3.2 on 2022-03-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pose',
            name='img_url',
            field=models.TextField(null=True),
        ),
    ]
