from pyexpat import model
from django.db import models
from accounts.models import *

class Pose(models.Model):
    added_by = models.ForeignKey(User,on_delete=models.CASCADE)
    pose_name = models.TextField()
    pose_description = models.TextField()
    pose_type = models.TextField()
    user_duration = models.FloatField()
    img_url = models.TextField(null=True)
    nose_x = models.FloatField()
    nose_y = models.FloatField()
    leftear_x = models.FloatField()
    leftear_y = models.FloatField()
    rightear_x = models.FloatField()
    rightear_y = models.FloatField()
    lefteye_x = models.FloatField()
    lefteye_y = models.FloatField()
    righteye_x = models.FloatField()
    righteye_y = models.FloatField()
    leftshoulder_x = models.FloatField()
    leftshoulder_y = models.FloatField()
    rightshoulder_x = models.FloatField()
    rightshoulder_y = models.FloatField()
    leftelbow_x = models.FloatField()
    leftelbow_y = models.FloatField()
    rightelbow_x = models.FloatField()
    rightelbow_y = models.FloatField()
    leftwrist_x = models.FloatField()
    leftwrist_y = models.FloatField()
    rightwrist_x = models.FloatField()
    rightwrist_y = models.FloatField()
    lefthip_x = models.FloatField()
    lefthip_y = models.FloatField()
    righthip_x = models.FloatField()
    righthip_y = models.FloatField()
    leftknee_x = models.FloatField()
    leftknee_y = models.FloatField()
    rightknee_x = models.FloatField()
    rightknee_y = models.FloatField()
    leftankle_x = models.FloatField()
    leftankle_y = models.FloatField()
    rightankle_x = models.FloatField()
    rightankle_y = models.FloatField()

class UserProfile(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    full_name = models.TextField()
    age = models.IntegerField()
    gender = models.CharField(max_length=10)
    height = models.IntegerField()
    weight = models.IntegerField()
    bmi = models.FloatField()

class UserPose(models.Model):
    pose = models.ForeignKey(Pose,on_delete=models.CASCADE)
    user = models.ForeignKey(UserProfile,on_delete=models.CASCADE)
    points_earned = models.IntegerField()